workflows:
  android_build:
    name: Build Android (with build_runner)
    environment:
      flutter: stable
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          set -e
          flutter pub get

      - name: Generate code (build_runner)
        script: |
          set -e
          flutter pub get  # Ataovy azo antoka fa mahita ny packages rehetra izy
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Android APK
        script: |
          set -e
          echo "Building release APK..."
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    cache:
      - .pub-cache
      - build
