import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'config/routes/app_routes.dart';
import 'package:firebase_core/firebase_core.dart';
// Firebase options generated by the FlutterFire CLI. If you don't have
// this file, run `flutterfire configure` to generate `firebase_options.dart`.
import 'firebase_options.dart';
import 'core/data/hive_database.dart';
import 'core/service_locator.dart' as di;
import 'core/theme/app_theme.dart';
import 'core/theme/theme_cubit.dart';
import 'core/utils/snackbar_helper.dart';
import 'core/locale/language_cubit.dart';
// Localization removed: hardcoded French strings used across the app.
import 'features/billing/presentation/bloc/billing_bloc.dart';
import 'features/product/presentation/bloc/product_bloc.dart';
import 'features/shop/presentation/bloc/shop_bloc.dart';
import 'features/settings/presentation/bloc/printer_bloc.dart';
import 'features/settings/presentation/bloc/printer_event.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase before other services so auth is available app-wide.
  try {
    // Prefer passing the generated options for the current platform so
    // Firebase initializes with the correct project configuration.
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e, st) {
    // If initialization fails (missing firebase_options.dart, bad config,
    // or platform misconfiguration), log the error and continue so the
    // rest of the app can start and handle auth-related errors gracefully.
    // The developer should check the Firebase setup locally.
    // ignore: avoid_print
    print('Firebase initialization error: $e');
    // ignore: avoid_print
    print(st);
    try {
      // Fallback to a default initialize in case options are not available.
      await Firebase.initializeApp();
    } catch (_) {}
  }
  await HiveDatabase.init();
  await di.init();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider<ProductBloc>(
            create: (context) => di.sl<ProductBloc>()..add(LoadProducts())),
        BlocProvider<ShopBloc>(
            create: (context) => di.sl<ShopBloc>()..add(LoadShopEvent())),
        BlocProvider<BillingBloc>(
            create: (context) =>
                BillingBloc(getProductByBarcodeUseCase: di.sl())),
        BlocProvider<PrinterBloc>(
            create: (context) => di.sl<PrinterBloc>()..add(InitPrinterEvent())),
        // Theme management Cubit
        BlocProvider<ThemeCubit>(
          create: (_) => ThemeCubit()..loadFromPersistence(),
        ),
        // Language / Locale Cubit (persisted)
        BlocProvider<LanguageCubit>(
          create: (_) => LanguageCubit()..loadFromPersistence(),
        ),
      ],
      child: BlocBuilder<ThemeCubit, ThemeMode>(
        builder: (context, mode) {
          return MaterialApp.router(
            // App is hardcoded to French. Remove localization delegates.
            locale: const Locale('fr'),
            title: 'GRC POS SYSTEM',
            // Keep the base themes from AppTheme but inject our global SnackBar style
            theme: AppTheme.lightTheme.copyWith(
              snackBarTheme: const SnackBarThemeData(
                behavior: SnackBarBehavior.floating,
                shape: StadiumBorder(),
                backgroundColor: Color(0xFFD32F2F), // default error red
                elevation: 6.0,
                contentTextStyle: TextStyle(
                  color: Colors.white,
                  fontWeight: FontWeight.bold,
                  fontSize: 15.0,
                ),
              ),
            ),
            darkTheme: AppTheme.darkTheme.copyWith(
              snackBarTheme: const SnackBarThemeData(
                behavior: SnackBarBehavior.floating,
                shape: StadiumBorder(),
                backgroundColor: Color(0xFFD32F2F),
                elevation: 6.0,
                contentTextStyle: TextStyle(
                  color: Colors.white,
                  fontWeight: FontWeight.bold,
                  fontSize: 15.0,
                ),
              ),
            ),
            // Use the ThemeCubit-controlled mode so the UI can toggle
            // between Dark and Light. ThemeCubit defaults to Dark now.
            themeMode: mode,
            // Use global scaffold messenger key so the helper can show snackbars
            scaffoldMessengerKey: scaffoldMessengerKey,
            routerConfig: router,
            debugShowCheckedModeBanner: false,
          );
        },
      ),
    );
  }
}
