import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'config/routes/app_routes.dart';
import 'package:firebase_core/firebase_core.dart';
// Firebase options generated by the FlutterFire CLI. If you don't have
// this file, run `flutterfire configure` to generate `firebase_options.dart`.
import 'firebase_options.dart';
import 'core/data/hive_database.dart';
import 'core/service_locator.dart' as di;
import 'core/theme/app_theme.dart';
import 'core/theme/theme_cubit.dart';
import 'core/widgets/subscription_guard.dart';
import 'core/utils/snackbar_helper.dart';
import 'core/locale/language_cubit.dart';
// Localization removed: hardcoded French strings used across the app.
import 'features/billing/presentation/bloc/billing_bloc.dart';
import 'features/product/presentation/bloc/product_bloc.dart';
import 'features/shop/presentation/bloc/shop_bloc.dart';
import 'features/settings/presentation/bloc/printer_bloc.dart';
import 'features/settings/presentation/bloc/printer_event.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Capture uncaught Flutter framework errors and Zone errors so we can
  // log them — this helps diagnose white-screen issues that only appear
  // in release builds (Codemagic). These print statements will appear in
  // CI logs or device logs.
  FlutterError.onError = (details) {
    // ignore: avoid_print
    print('FlutterError: ${details.exceptionAsString()}');
    // ignore: avoid_print
    print(details.stack);
  };

  await runZonedGuarded(() async {
    // Initialize Firebase before other services so auth is available app-wide.
    // NOTE: Firebase initialization is skipped when using mock data to allow
    // running the app without Firebase billing/configuration in CI or local
    // environments. Toggle the flag in `lib/core/config/mock_config.dart`.
    try {
      // Import the mock flag lazily to avoid import cycles during tests.
      // If mock mode is enabled we skip Firebase initialization.
      const bool useMock =
          bool.fromEnvironment('USE_MOCK_FIRESTORE', defaultValue: true);
      if (!useMock) {
        // Prefer passing the generated options for the current platform so
        // Firebase initializes with the correct project configuration.
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        );
        // ignore: avoid_print
        print('Firebase initialized with generated options');
      } else {
        // ignore: avoid_print
        print('Running in MOCK mode: Firebase initialization skipped');
      }
    } catch (e, st) {
      // If initialization fails, log and attempt fallback.
      // ignore: avoid_print
      print('Firebase initialization error: $e');
      // ignore: avoid_print
      print(st);
      try {
        await Firebase.initializeApp();
        // ignore: avoid_print
        print('Firebase initialized with default options');
      } catch (e2, st2) {
        // ignore: avoid_print
        print('Firebase fallback init failed: $e2');
        // ignore: avoid_print
        print(st2);
      }
    }

    // Initialize local DB and service locator
    try {
      await HiveDatabase.init();
      await di.init();
    } catch (e, st) {
      // ignore: avoid_print
      print('Initialization error (Hive/DI): $e');
      // ignore: avoid_print
      print(st);
    }

    runApp(const MyApp());
  }, (error, stack) {
    // Log any uncaught asynchronous error
    // ignore: avoid_print
    print('Unhandled zone error: $error');
    // ignore: avoid_print
    print(stack);
  });
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider<ProductBloc>(
            create: (context) => di.sl<ProductBloc>()..add(LoadProducts())),
        BlocProvider<ShopBloc>(
            create: (context) => di.sl<ShopBloc>()..add(LoadShopEvent())),
        BlocProvider<BillingBloc>(
            create: (context) =>
                BillingBloc(getProductByBarcodeUseCase: di.sl())),
        BlocProvider<PrinterBloc>(
            create: (context) => di.sl<PrinterBloc>()..add(InitPrinterEvent())),
        // Theme management Cubit
        BlocProvider<ThemeCubit>(
          create: (_) => ThemeCubit()..loadFromPersistence(),
        ),
        // Language / Locale Cubit (persisted)
        BlocProvider<LanguageCubit>(
          create: (_) => LanguageCubit()..loadFromPersistence(),
        ),
      ],
      child: BlocBuilder<ThemeCubit, ThemeMode>(
        builder: (context, mode) {
          return SubscriptionGuard(
            child: MaterialApp.router(
              // App is hardcoded to French. Remove localization delegates.
              locale: const Locale('fr'),
              title: 'GRC POS SYSTEM',
              // Keep the base themes from AppTheme but inject our global SnackBar style
              theme: AppTheme.lightTheme.copyWith(
                snackBarTheme: const SnackBarThemeData(
                  behavior: SnackBarBehavior.floating,
                  shape: StadiumBorder(),
                  backgroundColor: Color(0xFFD32F2F), // default error red
                  elevation: 6.0,
                  contentTextStyle: TextStyle(
                    color: Colors.white,
                    fontWeight: FontWeight.bold,
                    fontSize: 15.0,
                  ),
                ),
              ),
              darkTheme: AppTheme.darkTheme.copyWith(
                snackBarTheme: const SnackBarThemeData(
                  behavior: SnackBarBehavior.floating,
                  shape: StadiumBorder(),
                  backgroundColor: Color(0xFFD32F2F),
                  elevation: 6.0,
                  contentTextStyle: TextStyle(
                    color: Colors.white,
                    fontWeight: FontWeight.bold,
                    fontSize: 15.0,
                  ),
                ),
              ),
              // Use the ThemeCubit-controlled mode so the UI can toggle
              // between Dark and Light. ThemeCubit defaults to Dark now.
              themeMode: mode,
              // Use global scaffold messenger key so the helper can show snackbars
              scaffoldMessengerKey: scaffoldMessengerKey,
              routerConfig: router,
              debugShowCheckedModeBanner: false,
            ),
          );
        },
      ),
    );
  }
}
